const fs=require('fs');const path=require('path');const assert=require('assert');
const app=fs.readFileSync(path.join(__dirname,'..','assets','app.js'),'utf8');
const client=fs.readFileSync(path.join(__dirname,'..','assets','ai-client.js'),'utf8');
const orchestrator=fs.readFileSync(path.join(__dirname,'..','assets','deep-analysis-orchestrator.js'),'utf8');
assert.ok(orchestrator.includes('automatic-silent-enhancement-v2'));
assert.ok(app.includes('void enrichAnalysisWithAi'));
assert.ok(app.includes('taqareer-background-enhancement'));
assert.ok(app.includes('$("analysisModeChip").textContent = "تحليل تربوي عميق"'));
assert.ok(!app.includes('محاولة تحسين ذكي'));
assert.ok(!app.includes('التقرير المحلي جاهز الآن'));
assert.ok(!app.includes('تحسين Gemini اختياري جارٍ'));
assert.ok(client.includes('enhanceFastDetailed'));
assert.ok(client.includes('timeoutMs: 16000'));
console.log('PASS analysis starts automatic silent background enhancement without retry UI');
