const fs=require('fs');const path=require('path');const assert=require('assert');
const app=fs.readFileSync(path.join(__dirname,'..','assets','app.js'),'utf8');
const runtime=fs.readFileSync(path.join(__dirname,'..','assets','runtime-config.js'),'utf8');
const edge=fs.readFileSync(path.join(__dirname,'..','supabase','functions','analyze-educational-form','index.ts'),'utf8');
assert.ok(app.includes('notice.classList.add("hidden")'));
assert.ok(app.includes('showPerformanceDiagnostics !== true'));
assert.ok(runtime.includes('showPerformanceDiagnostics: false'));
for(const forbidden of ['محاولة تحسين ذكي','إعادة تحسين Gemini','التقرير مكتمل دون انتظار']) assert.ok(!app.includes(forbidden),forbidden);
assert.ok(edge.includes('gemini-3.5-flash-lite'));
assert.ok(edge.includes('geminiRequestWithFallback'));
assert.ok(edge.includes('modelIsUnavailable'));
console.log('PASS automatic enhancement is silent and model availability is handled server-side');
