const fs=require('fs');const path=require('path');const vm=require('vm');const ts=require('typescript');const assert=require('assert');
const source=fs.readFileSync(path.join(__dirname,'..','supabase','functions','analyze-educational-form','index.ts'),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
let handler=null;
const sandbox={console,crypto,TextEncoder,Uint8Array,performance,structuredClone,Request,Response,Headers,setTimeout,clearTimeout,Math,JSON,
 Deno:{env:{get:n=>({GEMINI_API_KEY:'k',GEMINI_MODEL:'gemini-2.5-flash',TAQAREER_ALLOWED_ORIGINS:'*',TAQAREER_ACCESS_CODE:''}[n])},serve:fn=>handler=fn},
 fetch:async(_u,o)=>{const request=JSON.parse(o.body);const payload=JSON.parse(request.contents[0].parts[0].text);const scope=payload.scope;const patches=[
  {targetType:'qualityTool',targetId:'tool.a',field:'interpretation',text:'تفسير أداة',items:[],evidenceRefs:['metric:n']},
  {targetType:'monitoring',targetId:'monitoring.a',field:'measure',text:'قياس',items:[],evidenceRefs:['metric:n']}
 ];const result={contractVersion:'4.1.0',segment:'governance',deepAnalysisUnits:[],patches,additionalCautions:[],missingDataRequests:[]};return new Response(JSON.stringify({modelVersion:'m',candidates:[{finishReason:'STOP',content:{parts:[{text:JSON.stringify(result)}]}}],usageMetadata:{}}),{status:200,headers:{'Content-Type':'application/json'}});}
};vm.createContext(sandbox);vm.runInContext(js,sandbox);
function payload(scope){return {segment:'governance',scope,taskId:`governance.${scope}`,reconciliationContract:{version:'3.0.0',rules:{maxDeepAnalysisUnits:0,maxPatches:6},deepAnalysisTargets:[],patchTargets:{findings:[],interventions:[],qualityTools:scope==='quality'?[{id:'tool.a',allowedFields:['interpretation']}]:[],monitoring:scope==='monitoring'?[{id:'monitoring.a',allowedFields:['measure']}]:[]}},deterministicAnalysis:{metrics:[{id:'n',value:1}],evidenceCatalog:[{ref:'metric:n',text:'1'}]},availableEvidenceRefs:['metric:n'],data:{mode:'derived-evidence-only'}};}
(async()=>{for(const scope of ['quality','monitoring']){const req=new Request('https://e.test',{method:'POST',headers:{'Content-Type':'application/json','Origin':'https://x'},body:JSON.stringify({operation:'enrich_segment',payload:payload(scope)})});const res=await handler(req);const body=await res.json();assert.strictEqual(res.status,200,JSON.stringify(body));assert.strictEqual(body.result.patches.length,1);assert.strictEqual(body.result.patches[0].targetType,scope==='quality'?'qualityTool':'monitoring');assert.strictEqual(body.serverTiming.taskId,`governance.${scope}`);assert.strictEqual(body.serverTiming.scope,scope);}console.log('PASS edge isolates governance quality and monitoring scopes');})().catch(e=>{console.error(e);process.exit(1);});
