const fs=require('fs');
const path=require('path');
const assert=require('assert');
const source=fs.readFileSync(path.join(__dirname,'..','supabase','functions','analyze-educational-form','index.ts'),'utf8');
assert.ok(source.includes('operation === "enrich"'));
assert.ok(source.includes('operation === "enrich_segment"'));
assert.ok(source.includes('validateDeepAnalysisDelta'));
assert.ok(source.includes('callDeepEnrichment'));
assert.ok(source.includes('callSegmentEnrichment'));
assert.ok(source.includes('SEGMENT_PROTOCOL_VERSION = "4.1.0"'));
assert.ok(source.includes('class SegmentGenerationError'));
assert.ok(source.includes('taskId'));
assert.ok(source.includes('scope'));
assert.ok(source.includes('responseMimeType: "application/json"'));
assert.ok(source.includes('responseSchemaSent: false'));
assert.ok(source.includes('isolated-json-mode-server-validated'));
assert.ok(source.includes('failureType'));
console.log('PASS edge supports isolated task enrichment, server-side validation, and structured failure diagnostics');
