const fs=require('fs');
const path=require('path');
const assert=require('assert');
const source=fs.readFileSync(path.join(__dirname,'..','supabase','functions','analyze-educational-form','index.ts'),'utf8');
assert.ok(source.includes('operation === "enrich"'));
assert.ok(source.includes('operation === "enrich_segment"'));
assert.ok(source.includes('validateDeepAnalysisDelta'));
assert.ok(source.includes('callDeepEnrichment'));
assert.ok(source.includes('callSegmentEnrichment'));
assert.ok(source.includes('SEGMENT_PROTOCOL_VERSION = "4.0.0"'));
assert.ok(source.includes('SEGMENT_NAMES'));
assert.ok(source.includes('candidate.finishReason === "MAX_TOKENS"'));
assert.ok(source.includes('responseMimeType: "application/json"'));
assert.ok(source.includes('responseSchemaSent: false'));
assert.ok(source.includes('لا تنشئ تدخلًا أو مرحلة متابعة أو أداة جودة أو استنتاجًا موازيًا'));
assert.ok(source.includes('التدخلات التنفيذية') || source.includes('interventions'));
console.log('PASS edge supports legacy deep delta and isolated segmented enrichment without complex response schema');
