const fs=require('fs');const path=require('path');const assert=require('assert');
const app=fs.readFileSync(path.join(__dirname,'..','assets','app.js'),'utf8');
const orchestrator=fs.readFileSync(path.join(__dirname,'..','assets','deep-analysis-orchestrator.js'),'utf8');
assert.ok(orchestrator.includes('automatic-silent-enhancement-v2'));
assert.ok(app.includes('void enrichAnalysisWithAi'));
assert.ok(!app.includes('التقرير المحلي جاهز الآن'));
assert.ok(!app.includes('محاولة تحسين ذكي'));
assert.ok(orchestrator.includes('sampleRows.slice(0, 6)'));
assert.ok(orchestrator.includes('lines.slice(0, 100)'));
assert.ok(orchestrator.includes('qualityTools: []'));
assert.ok(orchestrator.includes('monitoring: []'));
assert.ok(!orchestrator.includes('runPool('));
console.log('PASS automatic silent payload uses one compact request without task fan-out');
