const fs=require('fs'),path=require('path'),assert=require('assert');
const app=fs.readFileSync(path.join(__dirname,'..','assets','app.js'),'utf8');
const edge=fs.readFileSync(path.join(__dirname,'..','supabase','functions','analyze-educational-form','index.ts'),'utf8');
const ai=fs.readFileSync(path.join(__dirname,'..','assets','ai-client.js'),'utf8');
assert.ok(app.includes('tableAiLimit()'));
assert.ok(app.includes('return 16;'),'known score tables should use a tiny context sample');
assert.ok(app.includes('sampleRows: rows'));
assert.ok(!app.includes('state.rows.slice(0, 220)'));
assert.ok(app.includes('ظهرت الحسابات والرسوم فورًا'));
assert.ok(app.includes('إعادة تحسين Gemini فقط'));
assert.ok(app.includes('segmented-deep-analysis-v4'));
assert.ok(app.includes('TaqareerDeepOrchestrator'));
assert.ok(ai.includes('enrich_segment'));
assert.ok(app.includes('TaqareerReconciliation.reconcile'));
assert.ok(app.includes('cacheGet(cacheKey)'));
assert.ok(app.includes('aiServerTiming'));
assert.ok(edge.includes('gemini-2.5-flash-lite'));
assert.ok(edge.includes('prepareEnrichmentPayload'));
assert.ok(edge.includes('compactMode'));
assert.ok(edge.includes('SEGMENT_PROTOCOL_VERSION'));
assert.ok(edge.includes('prepareSegmentPayload'));
assert.ok(edge.includes('callSegmentEnrichment'));
assert.ok(edge.includes('serverTiming'));
console.log('PASS fast payload, progressive UI, v3 cache invalidation and deep-delta retry contract');
