const fs=require('fs');
const vm=require('vm');
const path=require('path');
const assert=require('assert');
const {webcrypto}=require('crypto');
class StorageMock{constructor(){this.map=new Map();}getItem(k){return this.map.has(k)?this.map.get(k):null;}setItem(k,v){this.map.set(String(k),String(v));}removeItem(k){this.map.delete(String(k));}}
const root=path.join(__dirname,'..');
const sandbox={window:{},console,structuredClone,JSON,Math,Date,Set,Map,Object,Array,String,Number,WeakSet,TextEncoder,crypto:webcrypto,performance,localStorage:new StorageMock(),setTimeout,clearTimeout};
sandbox.globalThis=sandbox;sandbox.window=sandbox;vm.createContext(sandbox);
for(const file of ['performance-pipeline.js','deep-analysis-orchestrator.js']) vm.runInContext(fs.readFileSync(path.join(root,'assets',file),'utf8'),sandbox);
const api=sandbox.TaqareerDeepOrchestrator;
assert.strictEqual(api.VERSION,'0.9.7');
assert.strictEqual(api.PROTOCOL_VERSION,'5.1.0');
const contract={version:'3.0.0',family:'scores',rules:{},executive:{id:'executive'},deepAnalysisTargets:[1,2,3,4].map(n=>({id:`diagnostic.${n}`,title:`د${n}`,currentAnalysis:'تحليل محلي طويل '.repeat(30),evidenceRefs:['metric:n']})),patchTargets:{findings:[1,2,3,4,5].map(n=>({id:`finding.${n}`,title:`ن${n}`,statement:'نتيجة',educationalImpact:'أثر',recommendedAction:'إجراء',evidenceRefs:['metric:n']})),interventions:[1,2,3,4].map(n=>({id:`intervention.${n}`,issue:`ف${n}`,action:'إجراء محلي',successIndicator:'مؤشر',evidenceRefs:['metric:n']})),qualityTools:[{id:'quality.a',name:'أداة'}],monitoring:[{id:'monitoring.a',stage:'متابعة'}]}};
const basePayload={locale:'ar-OM',source:{name:'aaaa.xlsx'},recognizedType:{id:'assessment_component'},quality:{completeness:100},privacy:{personalDataMasked:true},data:{headers:['م','اسم الطالب','الدرجة'],sampleRows:Array.from({length:16},(_,i)=>({_evidenceRef:`row:${i+1}`,values:[i+1,'[محجوب]',20]}))},deterministicAnalysis:{kind:'scores',typeId:'assessment_component',executiveTitle:'تقرير',executiveSummary:'ملخص',metrics:Array.from({length:28},(_,i)=>({id:i?'m'+i:'n',label:'مؤشر',value:i,evidenceRef:i?`metric:m${i}`:'metric:n'})),charts:Array.from({length:8},(_,i)=>({id:'c'+i,type:'bar',title:'رسم',data:Array.from({length:24},(_,j)=>({x:j,y:j}))})),limitations:['قيد'],evidenceCatalog:[{ref:'metric:n',text:'268'}]},reconciliationContract:contract,availableEvidenceRefs:['metric:n',...Array.from({length:16},(_,i)=>`row:${i+1}`)]};
let calls=0;
let lastPayload=null;
const ai={async enhanceFastDetailed(payload){calls++;lastPayload=payload;return{result:{contractVersion:'5.1.0',deepAnalysisUnits:[{targetId:'diagnostic.1',analysis:'تحليل تربوي عميق',evidenceRefs:['metric:n'],confidence:'مرتفعة',implications:['أثر'],alternativeExplanations:[],limitations:[],dataRequests:[]}],patches:[{targetType:'finding',targetId:'finding.1',field:'educationalImpact',text:'أثر محسن',items:[],evidenceRefs:['metric:n']}],additionalCautions:[],missingDataRequests:[]},model:'gemini-fast',clientTiming:{durationMs:5},serverTiming:{fastSingle:true,acceptedDeepAnalysisUnits:1,acceptedPatches:1}};}};
(async()=>{
  const first=await api.run({basePayload,ai,performanceApi:sandbox.TaqareerPerformance});
  assert.strictEqual(calls,1);
  assert.strictEqual(first.cacheHit,false);
  assert.ok(first.payloadChars<18000,`payload too large: ${first.payloadChars}`);
  assert.strictEqual(lastPayload.reconciliationContract.patchTargets.qualityTools.length,0);
  assert.strictEqual(lastPayload.reconciliationContract.patchTargets.monitoring.length,0);
  assert.strictEqual(lastPayload.data.sampleRows.length,6);
  const second=await api.run({basePayload,ai,performanceApi:sandbox.TaqareerPerformance});
  assert.strictEqual(calls,1,'second identical analysis must use cache');
  assert.strictEqual(second.cacheHit,true);
  console.log('PASS single fast enhancer uses one request, compact payload and cache');
})().catch(e=>{console.error(e);process.exit(1);});
